# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76a7843eb74e4819eda5d09e33e4c5fe2199e030281cd0286fdb6fbfd184150ba82f27dd379a9f71962cf94b4043742b548858f84f83e3a409b742f14cdb53f7

test:
  secret_key_base: 00958839d3b8b7930a5b4b40bb2aa6b87c10ec358c89e6e809aec1869ac9939718835b90b26c4861518758f026be4375c6c0fe1e3c76cfc6542414997a5446ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
